# =====================================
# SENIM FURNITURE - Application Config
# =====================================
spring.application.name=senim-furniture

# Server
server.port=8081

# Database - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/senim_furniture
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.senim.furniture=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Groq (FREE - no credit card)
groq.api.key=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
